{
    'name': 'SMIP',
    'version': '1.0',
    'summary': 'SMIP Summery',
    'description': 'SMIP Description',
    'category': 'Shkolla',
    'author': 'Jeton',
    'website': 'website',
    'license': 'LGPL-3',
    'depends': ['base'],
    'data': ['views/nxenes_view.xml', 'views/lenda_view.xml'],
    'installable': True,
    'auto_install': False,
    'application': True,
}
